all: json_haskell json_haskell_atto

json_haskell: json_haskell.hs
	ghc json_haskell.hs

json_haskell_atto: json_haskell_atto.hs
	ghc json_haskell_atto.hs

clean:
	rm -f json_haskell json_haskell_atto
